### ISSUE TITLE
glitch through world

### ISSUE THREAD

**Issue by NeuroTypicalCure** [vyse12138/minecraft-threejs#13]
if you stand under a block and then place at your feet or jump you fall through the world

**Comment by vyse12138** [comment]
Hey mate, thanks for the feedback!

If you tried to place a block at your feet, [this part of the code](https://github.com/vyse12138/minecraft-threejs/blob/main/src/control/index.ts#L345) should have stoped u from doing that.

And if you stand under a block and then jump, the [up-direction collide handler](https://github.com/vyse12138/minecraft-threejs/blob/main/src/control/index.ts#L663) should let u bounce back to the ground.

So I'm not able to reproduce glitch... do u mind providing a screenshot or demo video? Thanks!

**Comment by NeuroTypicalCure** [comment]
Heey, love your project

This is with the assumption that your demo is up to date, have you tried spamming?
Digging the bedrock and jumping underneath a block seems easier to pull off, at quick glance it doesn't seem like you reset to the block position and manipulate the velocity instead, this can still force you through something when you're moving fast enough, I'm no expert though.
I can try capturing on video later if you want

**Comment by NeuroTypicalCure** [comment]
your demo wasn't up to date, I built it and glitch was fixed, mb
